DROP TABLE IF EXISTS credentials CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS texts CASCADE;
DROP TABLE IF EXISTS log_passes CASCADE;
DROP TABLE IF EXISTS binary_files CASCADE;