// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: binary_file.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BinaryFiles_Insert_FullMethodName = "/api.BinaryFiles/Insert"
	BinaryFiles_Get_FullMethodName    = "/api.BinaryFiles/Get"
	BinaryFiles_Update_FullMethodName = "/api.BinaryFiles/Update"
	BinaryFiles_Delete_FullMethodName = "/api.BinaryFiles/Delete"
	BinaryFiles_List_FullMethodName   = "/api.BinaryFiles/List"
)

// BinaryFilesClient is the client API for BinaryFiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BinaryFilesClient interface {
	Insert(ctx context.Context, in *InsertBinaryFileRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetBinaryFileResponse, error)
	Update(ctx context.Context, in *UpdateBinaryFileRequest, opts ...grpc.CallOption) (*UpdateBinaryFileResponse, error)
	Delete(ctx context.Context, in *DeleteBinaryFileRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListBinaryFileRequest, opts ...grpc.CallOption) (*ListBinaryFileResponse, error)
}

type binaryFilesClient struct {
	cc grpc.ClientConnInterface
}

func NewBinaryFilesClient(cc grpc.ClientConnInterface) BinaryFilesClient {
	return &binaryFilesClient{cc}
}

func (c *binaryFilesClient) Insert(ctx context.Context, in *InsertBinaryFileRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, BinaryFiles_Insert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binaryFilesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetBinaryFileResponse, error) {
	out := new(GetBinaryFileResponse)
	err := c.cc.Invoke(ctx, BinaryFiles_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binaryFilesClient) Update(ctx context.Context, in *UpdateBinaryFileRequest, opts ...grpc.CallOption) (*UpdateBinaryFileResponse, error) {
	out := new(UpdateBinaryFileResponse)
	err := c.cc.Invoke(ctx, BinaryFiles_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binaryFilesClient) Delete(ctx context.Context, in *DeleteBinaryFileRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, BinaryFiles_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binaryFilesClient) List(ctx context.Context, in *ListBinaryFileRequest, opts ...grpc.CallOption) (*ListBinaryFileResponse, error) {
	out := new(ListBinaryFileResponse)
	err := c.cc.Invoke(ctx, BinaryFiles_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinaryFilesServer is the server API for BinaryFiles service.
// All implementations must embed UnimplementedBinaryFilesServer
// for forward compatibility
type BinaryFilesServer interface {
	Insert(context.Context, *InsertBinaryFileRequest) (*InsertResponse, error)
	Get(context.Context, *GetRequest) (*GetBinaryFileResponse, error)
	Update(context.Context, *UpdateBinaryFileRequest) (*UpdateBinaryFileResponse, error)
	Delete(context.Context, *DeleteBinaryFileRequest) (*DeleteResponse, error)
	List(context.Context, *ListBinaryFileRequest) (*ListBinaryFileResponse, error)
	mustEmbedUnimplementedBinaryFilesServer()
}

// UnimplementedBinaryFilesServer must be embedded to have forward compatible implementations.
type UnimplementedBinaryFilesServer struct {
}

func (UnimplementedBinaryFilesServer) Insert(context.Context, *InsertBinaryFileRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedBinaryFilesServer) Get(context.Context, *GetRequest) (*GetBinaryFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBinaryFilesServer) Update(context.Context, *UpdateBinaryFileRequest) (*UpdateBinaryFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBinaryFilesServer) Delete(context.Context, *DeleteBinaryFileRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBinaryFilesServer) List(context.Context, *ListBinaryFileRequest) (*ListBinaryFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBinaryFilesServer) mustEmbedUnimplementedBinaryFilesServer() {}

// UnsafeBinaryFilesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BinaryFilesServer will
// result in compilation errors.
type UnsafeBinaryFilesServer interface {
	mustEmbedUnimplementedBinaryFilesServer()
}

func RegisterBinaryFilesServer(s grpc.ServiceRegistrar, srv BinaryFilesServer) {
	s.RegisterService(&BinaryFiles_ServiceDesc, srv)
}

func _BinaryFiles_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertBinaryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryFilesServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryFiles_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryFilesServer).Insert(ctx, req.(*InsertBinaryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinaryFiles_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryFilesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryFiles_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryFilesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinaryFiles_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBinaryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryFilesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryFiles_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryFilesServer).Update(ctx, req.(*UpdateBinaryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinaryFiles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBinaryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryFilesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryFiles_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryFilesServer).Delete(ctx, req.(*DeleteBinaryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinaryFiles_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBinaryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryFilesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryFiles_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryFilesServer).List(ctx, req.(*ListBinaryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BinaryFiles_ServiceDesc is the grpc.ServiceDesc for BinaryFiles service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BinaryFiles_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BinaryFiles",
	HandlerType: (*BinaryFilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _BinaryFiles_Insert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BinaryFiles_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BinaryFiles_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BinaryFiles_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BinaryFiles_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "binary_file.proto",
}
