// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: binary_file.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HashFile  string                 `protobuf:"bytes,2,opt,name=hash_file,json=hashFile,proto3" json:"hash_file,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Meta      []byte                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *BinaryFile) Reset() {
	*x = BinaryFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryFile) ProtoMessage() {}

func (x *BinaryFile) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryFile.ProtoReflect.Descriptor instead.
func (*BinaryFile) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BinaryFile) GetHashFile() string {
	if x != nil {
		return x.HashFile
	}
	return ""
}

func (x *BinaryFile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BinaryFile) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type InsertBinaryFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	File *BinaryFile `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *InsertBinaryFileRequest) Reset() {
	*x = InsertBinaryFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBinaryFileRequest) ProtoMessage() {}

func (x *InsertBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*InsertBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{1}
}

func (x *InsertBinaryFileRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *InsertBinaryFileRequest) GetFile() *BinaryFile {
	if x != nil {
		return x.File
	}
	return nil
}

type InsertBinaryFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogPass *LogPass `protobuf:"bytes,1,opt,name=log_pass,json=logPass,proto3" json:"log_pass,omitempty"`
}

func (x *InsertBinaryFileResponse) Reset() {
	*x = InsertBinaryFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBinaryFileResponse) ProtoMessage() {}

func (x *InsertBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*InsertBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{2}
}

func (x *InsertBinaryFileResponse) GetLogPass() *LogPass {
	if x != nil {
		return x.LogPass
	}
	return nil
}

type GetBinaryFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *BinaryFile `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *GetBinaryFileResponse) Reset() {
	*x = GetBinaryFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryFileResponse) ProtoMessage() {}

func (x *GetBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*GetBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{3}
}

func (x *GetBinaryFileResponse) GetFile() *BinaryFile {
	if x != nil {
		return x.File
	}
	return nil
}

type UpdateBinaryFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	File *BinaryFile `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *UpdateBinaryFileRequest) Reset() {
	*x = UpdateBinaryFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBinaryFileRequest) ProtoMessage() {}

func (x *UpdateBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBinaryFileRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateBinaryFileRequest) GetFile() *BinaryFile {
	if x != nil {
		return x.File
	}
	return nil
}

type UpdateBinaryFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *BinaryFile `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *UpdateBinaryFileResponse) Reset() {
	*x = UpdateBinaryFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBinaryFileResponse) ProtoMessage() {}

func (x *UpdateBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*UpdateBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBinaryFileResponse) GetFile() *BinaryFile {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteBinaryFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteBinaryFileRequest) Reset() {
	*x = DeleteBinaryFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binary_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryFileRequest) ProtoMessage() {}

func (x *DeleteBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binary_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_binary_file_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBinaryFileRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DeleteBinaryFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_binary_file_proto protoreflect.FileDescriptor

var file_binary_file_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6c,
	0x6f, 0x67, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01,
	0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x39, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x17,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x43, 0x0a, 0x18, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x70,
	0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x67, 0x50, 0x61, 0x73, 0x73, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x73, 0x73,
	0x22, 0x3c, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x5d,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x3f, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x4c,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x8c, 0x02, 0x0a,
	0x0b, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x06,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x73, 0x68, 0x61, 0x6e,
	0x6b, 0x6f, 0x47, 0x4f, 0x2f, 0x47, 0x6f, 0x70, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binary_file_proto_rawDescOnce sync.Once
	file_binary_file_proto_rawDescData = file_binary_file_proto_rawDesc
)

func file_binary_file_proto_rawDescGZIP() []byte {
	file_binary_file_proto_rawDescOnce.Do(func() {
		file_binary_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_binary_file_proto_rawDescData)
	})
	return file_binary_file_proto_rawDescData
}

var file_binary_file_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_binary_file_proto_goTypes = []interface{}{
	(*BinaryFile)(nil),               // 0: api.BinaryFile
	(*InsertBinaryFileRequest)(nil),  // 1: api.InsertBinaryFileRequest
	(*InsertBinaryFileResponse)(nil), // 2: api.InsertBinaryFileResponse
	(*GetBinaryFileResponse)(nil),    // 3: api.GetBinaryFileResponse
	(*UpdateBinaryFileRequest)(nil),  // 4: api.UpdateBinaryFileRequest
	(*UpdateBinaryFileResponse)(nil), // 5: api.UpdateBinaryFileResponse
	(*DeleteBinaryFileRequest)(nil),  // 6: api.DeleteBinaryFileRequest
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
	(*User)(nil),                     // 8: api.User
	(*LogPass)(nil),                  // 9: api.LogPass
	(*GetRequest)(nil),               // 10: api.GetRequest
	(*DeleteResponse)(nil),           // 11: api.DeleteResponse
}
var file_binary_file_proto_depIdxs = []int32{
	7,  // 0: api.BinaryFile.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 1: api.InsertBinaryFileRequest.user:type_name -> api.User
	0,  // 2: api.InsertBinaryFileRequest.file:type_name -> api.BinaryFile
	9,  // 3: api.InsertBinaryFileResponse.log_pass:type_name -> api.LogPass
	0,  // 4: api.GetBinaryFileResponse.file:type_name -> api.BinaryFile
	8,  // 5: api.UpdateBinaryFileRequest.user:type_name -> api.User
	0,  // 6: api.UpdateBinaryFileRequest.file:type_name -> api.BinaryFile
	0,  // 7: api.UpdateBinaryFileResponse.file:type_name -> api.BinaryFile
	8,  // 8: api.DeleteBinaryFileRequest.user:type_name -> api.User
	1,  // 9: api.BinaryFiles.Insert:input_type -> api.InsertBinaryFileRequest
	10, // 10: api.BinaryFiles.Get:input_type -> api.GetRequest
	4,  // 11: api.BinaryFiles.Update:input_type -> api.UpdateBinaryFileRequest
	6,  // 12: api.BinaryFiles.Delete:input_type -> api.DeleteBinaryFileRequest
	2,  // 13: api.BinaryFiles.Insert:output_type -> api.InsertBinaryFileResponse
	3,  // 14: api.BinaryFiles.Get:output_type -> api.GetBinaryFileResponse
	5,  // 15: api.BinaryFiles.Update:output_type -> api.UpdateBinaryFileResponse
	11, // 16: api.BinaryFiles.Delete:output_type -> api.DeleteResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_binary_file_proto_init() }
func file_binary_file_proto_init() {
	if File_binary_file_proto != nil {
		return
	}
	file_registration_proto_init()
	file_log_pass_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_binary_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertBinaryFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertBinaryFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBinaryFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBinaryFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBinaryFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_binary_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBinaryFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binary_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_binary_file_proto_goTypes,
		DependencyIndexes: file_binary_file_proto_depIdxs,
		MessageInfos:      file_binary_file_proto_msgTypes,
	}.Build()
	File_binary_file_proto = out.File
	file_binary_file_proto_rawDesc = nil
	file_binary_file_proto_goTypes = nil
	file_binary_file_proto_depIdxs = nil
}
